export const CREATE_ACCOUNT = 'Create An Account';
export const ALREADY_ACCOUNT = 'Already have an account ? Login';
export const PASSWORD_MSG = 'Use 8 or more characters with a mix of letters, numbers & symbols';
export const PASSWORD_TEXT = 'Password';
export const LOGIN_TEXT = 'Log In';
export const SIGNUP_TEXT = 'Sign Up';
export const DONT_HAVE_ACCOUNT = 'Dont Have An Account ?';
export const FORGOT_PASS = 'Forgot your password ?'
export const CREATE_ARTICLE_TEXT = 'Create Article';
export const HOME = 'Home';
export const MY_ARTICLES = 'My Articles';
export const LOGOUT_TEXT = 'Logout';
