export const CREATE_ACCOUNT = 'Create An Account';
export const ALREADY_ACCOUNT = 'Already have an account ? Login';
export const PASSWORD_MSG = 'Use 8 or more characters with a mix of letters, numbers & symbols';
export const PASSWORD_TEXT = 'Password';
export const LOGIN_TEXT = 'Log In';
export const SIGNUP_TEXT = 'Sign Up';
export const DONT_HAVE_ACCOUNT = 'Dont Have An Account ?';
export const FORGOT_PASS = 'Forgot your password ?'
export const CREATE_ARTICLE_TEXT = 'Create Article';
export const HOME = 'Home';
export const MY_ARTICLES_TEXT = 'My Articles';
export const LOGOUT_TEXT = 'Logout';
export const TOP_STORIES = 'Top Stories';
export const UPDATE_ARTICLE_TEXT = 'Update Article';
export const CANCEL_BUTTON = 'Cancel';
export const DELETE_BUTTON = 'Delete';
export const DELETE_BOX_TEXT = 'Are you sure you want to delete this item? This action cannot be undone.';
